FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o producer producer.go types.go

RUN go build -o consumer consumer.go types.go

RUN go build -o silverpipeline ./silverpipelinecmd

RUN go build -o batchmanager ./batchmanagercmd

RUN go build -o streamingestmanager streamingestmanager.go

RUN go build -o streamingestmonitor streamingestmonitor.go
